# Generated by Django 5.0.1 on 2024-01-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_tag_remove_note_mod_time_alter_note_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-mod_time']},
        ),
        migrations.AddField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['mod_time'], name='mod_time_index'),
        ),
    ]
