# Generated by Django 5.0.1 on 2024-01-14 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_note_options_note_mod_time_note_mod_time_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='mod_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
